# Generated by Django 3.2.22 on 2023-10-23 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0084_supplier_is_locked'),
        ('product', '0189_merge_20230929_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product', to='account.supplier'),
        ),
    ]
