# Generated by Django 3.2.22 on 2023-10-24 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0085_alter_supplier_name'),
        ('product', '0190_product_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='account.supplier'),
        ),
    ]
