# Generated by Django 3.2.22 on 2023-10-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0191_producttype_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttype',
            name='kind',
            field=models.CharField(choices=[('normal', 'A standard product type.'), ('gift_card', 'A gift card product type.'), ('other', 'Other product type.')], max_length=32),
        ),
    ]
