# Generated by Django 3.2.22 on 2023-10-20 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0082_user_last_confirm_email_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('tax_number', models.CharField(blank=True, max_length=30, null=True)),
                ('business_scope', models.TextField(blank=True, null=True)),
                ('after_sale_name', models.CharField(blank=True, max_length=20)),
                ('after_sale_phone', models.CharField(blank=True, max_length=15)),
                ('contact_name', models.CharField(blank=True, max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('id_front', models.CharField(blank=True, max_length=256, null=True)),
                ('id_behind', models.CharField(blank=True, max_length=256, null=True)),
                ('author_letter', models.CharField(blank=True, max_length=256, null=True)),
                ('legal_id', models.CharField(blank=True, max_length=20)),
                ('legal_id_front', models.CharField(blank=True, max_length=256, null=True)),
                ('legal_id_behind', models.CharField(blank=True, max_length=256, null=True)),
                ('bankcard', models.CharField(blank=True, max_length=30)),
                ('bankname', models.CharField(blank=True, max_length=256)),
                ('sub_bankname', models.CharField(blank=True, max_length=256)),
                ('currency', models.CharField(blank=True, max_length=15)),
                ('country', models.CharField(blank=True, max_length=30)),
                ('product_info', models.TextField(blank=True)),
                ('product_safe_report', models.CharField(blank=True, max_length=256, null=True)),
                ('business_license', models.CharField(blank=True, max_length=256, null=True)),
                ('cert_qa', models.CharField(blank=True, max_length=256, null=True)),
                ('office_picture', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('C', 'Created'), ('A', 'Approving'), ('P', 'Passed'), ('R', 'Rejected')], default='C', max_length=1)),
                ('is_active', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.user')),
            ],
            options={
                'ordering': ('-date',),
                'permissions': (('manage_suppliers', 'Manage suppliers.'),),
            },
        ),
    ]
