# Generated by Django 3.2.22 on 2023-10-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0083_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
